#mysql slave 信息
[[mysql]]
server_id = 2002
host = "127.0.0.1"
port = 3306
username = "root"
password = "root"
binlog_filename = ""
binlog_position = 0
exclude = ["information_schema", "performance_schema", "mysql"]

# monitor的地址和rpc信息，用于获取任务信息
[monitor]
host = "127.0.0.1"
rpc_port = 1234

# 本机的rpcserver信息，用于接收monitor的rpc调用，对任务进行操作等
[rpc_server]
host = "127.0.0.1"
port = 1235

[nsq]
lookupd_http_address = ["127.0.0.1:4161"]
nsqd_tcp_address = []