rpc_ping_interval = "10s" #心跳时间
binlog_flush_interval = "5s" #binlog位置写入数据库的时间间隔
logfile = "/var/log/byroad/dispatcher.log"
loglevel = "Info" # Debug Info Warn Error Fatal Panic
db_instance_names = ["localhost", "test"]  #该实例的名称，可以使用多个，用来表示相应的数据库，用于区分不同实例上的任务
#db_instance_names = ["jumei_product"]
#mysql slave 信息
[mysql]
name = "localhost1"
server_id = 2002
host = "127.0.0.1"
port = 3306
username = "root"
password = "toor"
binlog_filename = ""
binlog_position = 0
exclude = ["information_schema", "performance_schema", "mysql"]
# include = ["test"]
interval = "60s" # interval to update information schema
timeout_to_reconnect = "10s" #超过该时间未收到binlog消息将重建连接

#[mysql]
#name = "jumei_product"
#server_id = 2017
#host = "192.168.20.71"
#port = 9001
#username = "plsys_r"
#password = "plsys_r20.71"
#binlog_filename = ""
#binlog_position = 0
#exclude = ["information_schema", "performance_schema", "mysql"]
#interval = "300s"
#timeout_to_reconnect = "10s" #超过该时间未收到binlog消息将重建连接

# monitor的地址和rpc信息，用于获取任务信息
[monitor]
host = "127.0.0.1"
rpc_port = 1234

# 本机的rpcserver信息，用于接收monitor的rpc调用，对任务进行操作等
[rpc_server]
host = "127.0.0.1"
port = 0 #随机选择端口
# desc = "" #该描述使用db_instance_name

[nsq]
# lookupd_http_address = ["127.0.0.1:4161"]
nsqd_tcp_address = ["127.0.0.1:4150"]
lookup_interval = "60s" # 向nsqlookupd轮询nsqd节点信息

# 保存binlog信息
[db_config]
host = "127.0.0.1"
port = 3306
username = "root"
password = "toor"
dbname = "byroad"
