rpc_ping_interval = "10s" #心跳时间
logfile = "/var/log/byroad/dispatcher.log"
loglevel = "Info" # Debug Info Warn Error Fatal Panic

# monitor的地址和rpc信息，用于获取任务信息
[monitor]
host = "127.0.0.1"
rpc_port = 1234

# 本机的rpcserver信息，用于接收monitor的rpc调用，对任务进行操作等
[rpc_server]
host = "127.0.0.1"
port = 0 #随机选择端口
desc = "dispatcher1"

[nsq]
# lookupd_http_address = ["127.0.0.1:4161"]
nsqd_tcp_address = ["127.0.0.1:4150"]
lookup_interval = "60s" # 向nsqlookupd轮询nsqd节点信息

[kafka]
hosts = ["192.168.49.63:9092"]
offset_processing_timeout = "10s"
offset_reset_offsets = false
#zk_addrs = ["192.168.49.63:2181"]
zk_addrs = ["127.0.0.1:2181"]
