debug = true
nsqlookupd_http_address = ["127.0.0.1:4161"]
rpcclient_lookup_interval = "60s" # 心跳时间
logfile = "/var/log/byroad/monitor.log"
loglevel = "Info" # Debug Info Warn Error Fatal Panic
[mysql]
host = "127.0.0.1"
port = 3306
username = "root"
password = "root"
dbname = "byroad"

#做为rpcserver监听信息
[rpcserver]
host = "127.0.0.1"
port = 1234

[web]
host = "127.0.0.1"
port = 4000
auth_url = "http://auth.jumeird.com"
#appkey = "560f13a69e4711e5a0ca842b2b738d12"
appkey = "457e3930b5cc11e589e1842b2b738d12"
appname = "bypass"
aliasname = "bypass"

[[mysql_instance]]
name = "localhost"
host = "127.0.0.1"
port = 3306
username = "root"
password = "root"
include = []
exclude = ["information_schema", "performance_schema", "mysql"]
