rpc_ping_interval = "10s"
[nsq]
lookupd_http_address = ["172.17.0.1:4161"]
nsqd_tcp_address = []

[monitor]
host = "127.0.0.1"
rpc_port = 1234

[rpc_server]
host = "127.0.0.1"
port = 1239
desc = "localhost:1239"
