rpc_ping_interval = "10s"
max_idle_conns_per_host = 1000
logfile = "/var/log/byroad/pusher.log"
loglevel = "Info" # Debug Info Warn Error Fatal Panic

[nsq]
lookupd_http_address = ["127.0.0.1:4161"]
max_concurrent_handler = 10

[monitor]
host = "127.0.0.1"
rpc_port = 1234

[rpc_server]
host = "127.0.0.1"
port = 0 # 随机选择端口
desc = "localhost:1239"

# 任务发送失败日志信息记录到数据库
[mysql]
host = "127.0.0.1"
port = 3306
username = "root"
password = ""
dbname = "byroad"

[alert]
user = ""
password = ""
sms_addr = "http://localhost:12344"
email_addr = "http://localhost:3123"
max_count = 10 #单位时间内超过次数将报警
period = "1m" #单位时间