rpc_ping_interval = "10s"
max_idle_conns_per_host = 1000
logfile = "/var/log/byroad/pusher.log"
loglevel = "Info" # Debug Info Warn Error Fatal Panic

[nsq]
lookupd_http_address = ["172.17.0.1:4161"]

[monitor]
host = "127.0.0.1"
rpc_port = 1234

[rpc_server]
host = "127.0.0.1"
port = 0 # 随机选择端口
desc = "localhost:1239"

# 任务发送失败日志信息记录到数据库
[mysql]
host = "127.0.0.1"
port = 3306
username = "root"
password = "root"
dbname = "byroad"
